SELECT STATE, NAME, SUM(EXTCOST) AS TOTAL_COST, RANK () OVER (PARTITION BY STATE ORDER BY SUM(EXTCOST) DESC) AS RANK_STATE_CUSTOMER
FROM INVENTORY_FACT F JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5
GROUP BY STATE, NAME
ORDER BY STATE;
