SELECT NAME, COUNT(*) AS TOTAL_TRANSACTIONS, RANK () OVER (ORDER BY COUNT(*) DESC) AS RANK_STATE_CUSTOMER, DENSE_RANK () OVER (ORDER BY COUNT(*) DESC) AS  RANK_STATE_CUSTOMER
FROM INVENTORY_FACT F JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
WHERE TRANSTYPEKEY = 5
GROUP BY NAME;