SELECT ZIP, CALYEAR,CALMONTH, SUM(EXTCOST) AS TOTAL_COST, SUM(SUM(EXTCOST)) OVER 
   (PARTITION BY ZIP, CALYEAR ORDER BY ZIP, CALYEAR, CALMONTH ROWS UNBOUNDED PRECEDING ) AS TOTAL_CUM_COST
FROM INVENTORY_FACT F JOIN CUST_VENDOR_DIM C ON F.CUSTVENDORKEY = C.CUSTVENDORKEY
                      JOIN DATE_DIM D ON D.DATEKEY = F.DATEKEY
WHERE TRANSTYPEKEY = 5
GROUP BY ZIP, CALYEAR, CALMONTH
ORDER BY ZIP, CALYEAR, CALMONTH;