SELECT CALYEAR,SECONDITEMID, SUM(EXTCOST) AS TOTAL_COST, RATIO_TO_REPORT (SUM(EXTCOST)) OVER (PARTITION BY CALYEAR) AS RATIO_TO_REPORT
FROM INVENTORY_FACT F JOIN ITEM_MASTER_DIM I ON F.ITEMMASTERKEY = I.ITEMMASTERKEY
                      JOIN DATE_DIM D ON F.DATEKEY = D.DATEKEY
WHERE TRANSTYPEKEY = 1
GROUP BY CALYEAR, SECONDITEMID
ORDER BY 1,3 DESC;