SELECT BPNAME, COMPANYKEY, CARRYINGCOST, RANK() OVER (ORDER BY CARRYINGCOST) AS RANK,
						   PERCENT_RANK() OVER (ORDER BY CARRYINGCOST) AS PERCENT_RANK,
						   CUME_DIST () OVER (ORDER BY CARRYINGCOST) AS CUME_DIST
                                        
FROM BRANCH_PLANT_DIM;