SELECT * FROM (
SELECT BPNAME,COMPANYKEY, CARRYINGCOST,CUME_DIST () OVER ( ORDER BY CARRYINGCOST) AS CUME_DIST                                         
FROM BRANCH_PLANT_DIM)
WHERE CUME_DIST >= 0.85;